services:
  pikav:
    image: timayz/pikav:0.20.1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pikav.rule=Host(`pikav.timada.localhost`)"
      - "traefik.http.routers.pikav.tls=true"
      - "traefik.http.routers.pikav.entrypoints=https"
    ports:
      - "6750:6750"
      - "6751:6751"
    volumes:
      - ./timada/pikav.yml:/etc/pikav/config.yml
    networks:
      - intranet
    command: pikav serve -c /etc/pikav/config.yml
    entrypoint: []

networks:
  intranet:
    name: timada
    external: true
