services:
  cockroach:
    image: cockroachdb/cockroach:v23.1.4
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    ports:
      - 26257:26257
    command: start-single-node --insecure
    networks:
      - intranet

networks:
  intranet:
    name: timada
    external: true

volumes:
  cockroach-data:
