services:
  cockroach:
    image: cockroachdb/cockroach:v23.2.0
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    ports:
      - 26257:26257
    command: start-single-node --insecure
    networks:
      - intranet

  # yugabyte:
  #   image: yugabytedb/yugabyte:2.20.1.0-b97
  #   volumes:
  #     - yugabyte-data:/home/yugabyte/yb_data
  #   ports:
  #     - 7000:7000
  #     - 9000:9000
  #     - 15433:15433
  #     - 5433:5433
  #     - 9042:9042
  #   command: bin/yugabyted start --base_dir=/home/yugabyte/yb_data --daemon=false
  #   networks:
  #     - intranet

  # pulsar:
  #   image: apachepulsar/pulsar:3.1.0
  #   volumes:
  #     - pulsar-data:/pulsar/data
  #   ports:
  #     - 6650:6650
  #   command: bin/pulsar standalone
  #   networks:
  #     - intranet

networks:
  intranet:
    name: timada
    external: true

volumes:
  cockroach-data:
  # yugabyte-data:
  # pulsar-data:
