services:
  cockroach:
    image: cockroachdb/cockroach:v23.1.10
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    ports:
      - 26257:26257
    command: start-single-node --insecure
    networks:
      - intranet

  # pulsar:
  #   image: apachepulsar/pulsar:3.1.0
  #   volumes:
  #     - pulsar-data:/pulsar/data
  #   ports:
  #     - 6650:6650
  #   command: bin/pulsar standalone
  #   networks:
  #     - intranet

networks:
  intranet:
    name: timada
    external: true

volumes:
  cockroach-data:
  # pulsar-data:
